# Generated by Django 6.0.6 on 2026-07-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('regular', 'Звичайний'), ('magnetic', 'Магнітний'), ('electric', 'Електричний')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(help_text='Час збірки в секундах')),
                ('scramble', models.CharField(max_length=100)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cube')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='tracker.session')),
            ],
        ),
    ]
