# Generated by Django 6.0.6 on 2026-07-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(0, 'Regular'), (1, 'Magnetic')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('scramble', models.CharField(max_length=100)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cube')),
            ],
        ),
    ]
