# Generated by Django 6.0.6 on 2026-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='type',
            field=models.CharField(choices=[('Regular', 0), ('Magnetic', 1)], max_length=100),
        ),
    ]
