# Generated by Django 6.0.6 on 2026-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cube_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='type',
            field=models.CharField(choices=[(0, 'Regular'), (1, 'Magnetic')], max_length=100),
        ),
    ]
