# Generated by Django 6.0.6 on 2026-07-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_cube_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Magnetic')]),
        ),
        migrations.CreateModel(
            name='Type_Of_Cubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cube')),
            ],
        ),
    ]
